/// <reference types="next/image-types/global" />

// next-env.d.ts is generated by next build/dev and is git-ignored, so
// tsc --noEmit in CI (which runs before the build) would not know the static
// image module types. This committed reference keeps typecheck stable.
export {};
