import type { Metadata } from "next";
import {
  BodyCopy,
  Container,
  DisplayHeading,
  Eyebrow,
  LinkButton,
  Section,
} from "@/components/primitives";
import { SITE_NAME, SITE_TAGLINE, findPage } from "@/lib/site";

/**
 * Per-route metadata built from the single route registry in `lib/site.ts`, so
 * title, description, canonical and Open Graph can never drift apart. The
 * canonical is always a path resolved against `metadataBase`
 * (https://lumensync.io) — never a deployment host.
 */
/**
 * The site-wide Open Graph card, generated by `app/opengraph-image.tsx`.
 *
 * Next.js does NOT merge a child segment's `openGraph` object into the
 * inherited one — it replaces it. Setting `openGraph` per route therefore used
 * to drop the root card, leaving fifteen of sixteen routes with no image and a
 * `summary` Twitter card instead of `summary_large_image`. Naming the image
 * here restores it for every route while keeping per-route title, description
 * and URL. A page that genuinely needs its own card can still override this.
 */
export const SITE_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
} as const;

export function pageMetadata(path: string): Metadata {
  const page = findPage(path);
  if (!page) return {};
  return {
    title: page.title,
    description: page.description,
    alternates: { canonical: path },
    openGraph: {
      url: path,
      title: page.title,
      description: page.description,
      images: [SITE_OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.description,
      images: [SITE_OG_IMAGE],
    },
  };
}

/**
 * Restrained structural placeholder for routes whose full implementation
 * belongs to a later work item. Establishes heading hierarchy and page rhythm
 * without inventing content.
 */
export function PageScaffold({
  path,
  eyebrow,
  children,
}: {
  path: string;
  eyebrow?: string;
  children?: React.ReactNode;
}) {
  const page = findPage(path);
  if (!page) return null;
  return (
    <Section aria-labelledby="page-heading">
      <Container>
        <div className="max-w-3xl">
          {eyebrow ? <Eyebrow>{eyebrow}</Eyebrow> : null}
          <span id="page-heading">
            <DisplayHeading>{page.title}</DisplayHeading>
          </span>
          <BodyCopy className="mt-6">{page.description}</BodyCopy>
          <div className="mt-8 flex flex-wrap gap-3">
            <LinkButton href="/request-demo" variant="primary">
              Request a Demo
            </LinkButton>
            <LinkButton href="/product" variant="secondary">
              Product Overview
            </LinkButton>
          </div>
        </div>
        {children}
      </Container>
    </Section>
  );
}
